version: '3'
services:
  # api:
  #   env_file:
  #     - .env
  #   # Create backend container
  #   build:
  #     context: ./api
  #     dockerfile: ./Dockerfile
  #     args:
  #       - CMC_API_KEY=${CMC_API_KEY?err}
  #       - API_PORT=${API_PORT?err}
  #       - NODE_VERSION=${NODE_VERSION?err}
  #   ports:
  #     - "8080:8080"
  #   container_name: letsgo-api
  #   restart: always
  web:
    env_file:
      - .env
    # Create backend container
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: ./app
      dockerfile: ./Dockerfile
      args:
        - CMC_API_KEY=${CMC_API_KEY?err}
        - API_PORT=${API_PORT?err}
        - NODE_VERSION=${NODE_VERSION?err}
        - NODE_ENV=${NODE_ENV?err}
    ports:
      - "3000:3000"
    container_name: letsgo-web
    restart: always

